### ISSUE TITLE
Proofing Tool GUI

### ISSUE THREAD

**Issue by RGB-es** [sbosio/rla-es#12]
No estoy seguro de que este sea el lugar apropiado, pero no encuentro un foro aquí en GitHub y no me es claro si el foro de RedIris seguirá siendo utilizado. Desde ya, pido disculpas si he equivocado lugar. 

Dado que no he visto que se mencionara en el antiguo sito me pareció oportuno avisar que Marco Pinto ha desarrollado una herramienta para facilitar la edición de diccionarios, ya sean ortográficos, de sinónimos o de separación en sílabas llamada «Proofing Tool GUI».

http://marcoagpinto.cidadevirtual.pt/proofingtoolgui.html

No la he probado, pero al parecer es fácil de utilizar y podría ser una ayuda para desarrollar el diccionario Español.

Saludos

**Comment by marcoagpinto** [comment]
Olá!

O Proofing Tool GUI já vai na build 115.

Actualmente já é possível editar Autocorrects e tem suporte para dicionários com "twofold" (a pessoa que me ajudou com o twofold foi-me enviando exemplos e comentários, para níveis superiores de recursividade não foi testado).

:-)

**Comment by olea** [comment]
> e tem suporte para dicionários com "twofold"

Hola @marcoagpinto:

¿Serías tan amable de explicar cómo funciona esa característica «twofold», por favor?

**Comment by marcoagpinto** [comment]
Olá!

Twofold is a flag that calls another flag (recursivity)

```
SET UTF-8

CIRCUMFIX Y

##### Possessive preposition prefixes (the 2nd one is excluded from the circumfix on purpose) #####
PFX j Y 2
PFX j 0 A/Y .
PFX j 0 B .

#### Possessive preposition suffixes for circumfixes (its, thereof, etc.) ####
SFX J Y 2
SFX J 0 G/jY .
SFX J 0 I/j . 
```

And the word:
a/J

But this example uses the CIRCUMFIX flag and I am trying to fix CIRCUMFIX.

For months that I have been trying to fix it.

**Comment by olea** [comment]
@marcoagpinto Thanks a lot for your fast answer.

The major handicap of the RLA-ES hunspell-es is we are maintaining redundant dictionaries for each region, due to the affix language features is not possible to use diff/patch or file inclusions to manage the differences. While the common parts are enormous the differences are significant enough to be included in each l10n scope.

Maybe PTG supports a workflow like this? If you are courious about how hunspell-es is composed maybe you'll want to check [make_dict.sh](https://github.com/sbosio/rla-es/blob/master/ortograf/herramientas/make_dict.sh).
